### ISSUE TITLE
Shapefile input for 'zones' command not valid

### ISSUE THREAD

**Issue by ererkka** [consbio/trefoil#55]
I’m trying to create zones using a shapefile like this:

    trefoil zones --attribute Clusters_c --like MERRA2_data\MERRA-2.tavg1_2d_lnd_Nx.20170101.SUB.nc4 gis\sweden.shp .

The input shapefile (`gis/sweden.shp`) is a valid shapefile, but trefoil throws me an error:

    Error: Invalid value for "INPUT": gis/sweden.shp is not a valid input file

I think this is because INPUT argument is created using `@file_in_arg` from `rasterio.rio.options`. I think that assumes that the input file should be some format supported by GDAL (see `rasterio.rio.options.file_in_handler` and `rasterio.shutil.exists`). Am I understanding something wrong here?

**Comment by brendan-ward** [comment]
@ererkka unfortunately, it sounds like it is an issue with `fiona` (which we use to read shapefiles) not being able to read your shapefile.

Since `fiona` is a dependency to `trefoil`, you should be able to use the `fiona` CLI in the same python environment as you installed `trefoil`:
https://github.com/Toblerity/Fiona#fiona-cli

`fio info --indent 2 gis/sweden.shp`

May tell you a bit more directly if `fiona` is not able to read it.

If you have `gdal` installed on your computer, running `gdalinfo gis/sweden.shp` may also tell you about any potential errors in your shapefile.  Note: `fiona` uses some of the `gdal/ogr` internals to read shapefiles, but through a different interface.

Lastly, what is the nature of `gis/sweden.shp`?  Is it a polygon, line, point file?  How was it created?  Something about that pipeline may inform us as to the issue.

**Comment by ererkka** [comment]
The shapefile consist of four polygons over Sweden, and they are in WGS84. From `fio info` I get:
<pre>
{
  "name": "sweden",
  "bounds": [
    10.982554050000035,
    55.33685324592171,
    24.16659005000005,
    69.06008174803289
  ],
  "schema": {
    "properties": {
      "NUTS_ID": "str:80",
      "Clusters_c": "str:254",
      "country": "str:10"
    },
    "geometry": "Polygon"
  },
  "count": 4,
  "crs": "EPSG:4326",
  "driver": "ESRI Shapefile",
  "crs_wkt": "GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4326\"]]"
}
</pre>

**Comment by ererkka** [comment]
Same thing :( 

It seems that the exception is raised by `rasterio.rio.options.file_in_handler()` (callback in `file_in_arg`) because `rasterio.shutil.exists('gis/sweden.shp')` returns `False`. I wonder why is trefoil using rasterio to check the file?

**Comment by brendan-ward** [comment]
@ererkka no idea why I was using `rasterio` for the shapefile, nor do I know how that ever worked.  Very sorry for that issue and for the delays in getting it resolved!

I was able to reproduce your issue, then resolved in the fix list above.   Please pull the latest from `master` on this repo, and try again.  If the fix works for you, I'll then push up to `pypi`.

**Comment by ererkka** [comment]
Now it works. Thank you very much!

**Comment by brendan-ward** [comment]
🎉 thank you for reporting this issue, @ererkka
